"""initial version

Revision ID: 45fd9deaf616
Revises: 
Create Date: 2021-03-17 05:05:34.267614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45fd9deaf616'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=20), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('first_connected', sa.DateTime(), nullable=True),
    sa.Column('is_connected', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=20), nullable=True),
    sa.Column('hardware_version', sa.String(length=20), nullable=True),
    sa.Column('software_version', sa.String(length=20), nullable=True),
    sa.Column('creation_time', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('interior_sensor', sa.String(length=20), nullable=True),
    sa.Column('exterior_sensor', sa.String(length=20), nullable=True),
    sa.Column('interior_temp', sa.String(length=7), nullable=True),
    sa.Column('exterior_temp', sa.String(length=7), nullable=True),
    sa.Column('grainbin_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    op.create_table('system_hardware',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=20), nullable=True),
    sa.Column('hardware_version', sa.String(length=20), nullable=True),
    sa.Column('interior_sensor', sa.String(length=20), nullable=True),
    sa.Column('exterior_sensor', sa.String(length=20), nullable=True),
    sa.Column('serial_number', sa.String(length=20), nullable=True),
    sa.Column('grainbin_reader_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_interface',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interface', sa.String(length=5), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_for_fm', sa.Boolean(), nullable=True),
    sa.Column('is_external', sa.Boolean(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_setup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_setup', sa.Boolean(), nullable=True),
    sa.Column('first_setup_time', sa.DateTime(), nullable=True),
    sa.Column('standalone_configuration', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_software',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('software_version', sa.String(length=20), nullable=True),
    sa.Column('software_version_last', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grainbin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('bus_number', sa.Integer(), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('average_temp', sa.String(length=7), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('system_wifi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=20), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('interface_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['interface_id'], ['system_interface.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_wifi')
    op.drop_table('grainbin')
    op.drop_table('system_software')
    op.drop_table('system_setup')
    op.drop_table('system_interface')
    op.drop_table('system_hardware')
    op.drop_table('device')
    op.drop_table('connection')
    # ### end Alembic commands ###
